### ISSUE TITLE
[no-promise-reject] Remove this rule - it's not in the scope of this project.

### ISSUE THREAD

**Issue by RebeccaStevens** [jonaskello/eslint-plugin-functional#102]
Promises are a type of [monad](https://en.wikipedia.org/wiki/Monad_(functional_programming)) which are definitely a part of functional programming.

The `no-promise-reject` rule is not only outside the scope of this project but it encourages promise antipatterns.

**Comment by RebeccaStevens** [comment]
@jonaskello Thoughts?

**Comment by jonaskello** [comment]
Yes, I would agree with this. In functional programming I think the way to handle errors is to return a value representing the error. This is what the reject function does. My only concern is if we are breaking anyone using this. So maybe wait for feedback for a few days and then we can remove it in next major.

**Comment by whatisaphone** [comment]
Since you asked for feedback, I'll write a bit.

We use this rule at $DAY_JOB. Generally I prefer using monadic error types (a sum type à la Haskell's `Either` or Rust's `Option`). There are many benefits to treating errors as ordinary values instead of giving them a special form of control flow. Notably in typescript you cannot annotate the type of a Promise rejection (we have `Promise<T>`, not `Promise<T, E>`). `Promise.reject` is the `async` equivalent of `throw`, so imo this rule belongs here just as much as the `no-throw` rule does.

**Comment by RebeccaStevens** [comment]
Hmmm, @whatisaphone  that is a good point that you make.

Maybe we should open an issue for typescript itself about adding `Promise<T, E>`. If promise rejections were typed, would you still need this rule?

**Comment by RebeccaStevens** [comment]
https://github.com/microsoft/TypeScript/issues/39680

**Comment by RebeccaStevens** [comment]
I'm going to close this issue. The rule get to stay for the foreseeable future.
