### ISSUE TITLE
Rename rules and options

### ISSUE THREAD

**Issue by RebeccaStevens** [jonaskello/eslint-plugin-functional#11]
Looking at other plugins, they are tending to move away from `no-` and `ignore` prefixes.

Some of our rules names are also inconsistent, some end with `statement` while others don't despite them both refering to statements.

### Rules

| Current Name             | New Name                  | Theme         |
| :----------------------- | :------------------------ | :------------ |
| prefer-readonly-type     |                           | No mutability |
| no-let                   | enforce-const             | No mutability |
| immutable-data           |                           | No mutability |
| no-method-signature      | prefer-property-signature | No mutability |
| no-this-expression       |                           | No OO         |
| no-class                 |                           | No OO         |
| no-mixed-type            |                           | No OO         |
| prefer-type-literal      |                           | No OO         |
| no-expression-statement  |                           | No statements |
| no-conditional-statement |                           | No statements |
| no-loop-statement        |                           | No statements |
| no-return-void           |                           | No statements |
| no-throw-statement       |                           | No exceptions |
| no-try-statement         |                           | No exceptions |
| no-promise-reject        |                           | No exceptions |
| functional-parameters    |                           | Currying      |

### Options

| Current Name           | New Name                     |
| :--------------------- | :--------------------------- |
| ignoreAccessorPattern  |  |
| ignoreLocal            |            |
| ignoreClass            |          |
| ignoreInterface        |      |
| ignorePattern          |          |
| allowMutableReturnType       |        |
| ignoreImmediateMutation         |         |
| allowArgumentsKeyword  |                              |
| allowNull              |                              |
| allowRestParameter     |                              |
| allowReturningBranches |                              |
| allowUndefined         |                              |
| assumeTypes            |                              |
| checkImplicit          |                              |
| checkInterfaces        |                              |
| checkTypeLiterals      |                              |
| enforceParameterCount  |                              |

------
**Name Suggestion Are Most Welcome**

**Comment by jonaskello** [comment]
I think I read somewhere about guidelines for naming rules. Don't remember if it was for tslint or eslint and now I cannot find it again :-/. Do you have some links to examples of other plugins?

Looking at the [built-in](https://eslint.org/docs/rules/) rules they seem to be mostly have the prefix `no-*` or `prefer-*`. Many have no prefix at all though.

**Comment by jonaskello** [comment]
There also the question if we should divide the rules into smaller more distinct rules, or have more thematic rules with more options. For example instead of `no-if-statement` and `no-switch-statment` we can have `no-conditional-statment`. There is also `no-expression-statment` which is about preventing statments. Perhaps all of them could be collapsed into `no-statements` with some options for the original cases. However if we collapse too far the options to cover everything might become complex. As usual it comes down to a trade-off. Anyway I think the way we are moving now is to join rules into more thematic rules which probably is a good thing as long as he options does not become too complex.

Another example is `no-throw`, `no-try`, `no-reject` which I think is all about avoiding exceptions. Perhaps they could be joined into a `no-exceptions` rule? Or maybe that would make the rule too complex?

**Comment by jonaskello** [comment]
`no-this`, `no-class` could probably be joined too?

**Comment by jonaskello** [comment]
Regarding `no-let` vs `enforce-const` that could make sense if we also add that it should enforce [const-assertions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions).

**Comment by jonaskello** [comment]
When considering the rule names and separation, perhaps it would be help to identify some main themes that are needed to make typescript functional. Something like:

* Immutability
* No statements
* No exceptions
* No object orientation

**Comment by RebeccaStevens** [comment]
I think it would be a good idea to merge `no-array-mutation` and `no-object-mutation` together into a single rule. Both these rules are quite similar under the hood and preform many of the aam

readonly-keyword	
readonly-array	
no-let
no-method-signature
no-delete	
no-this	
no-class	
no-mixed-interface	
no-expression-statement	
no-if-statement
no-loop-statement	
no-throw
no-try
no-reject

**Comment by RebeccaStevens** [comment]
*Didn't mean to close this.*

**Comment by RebeccaStevens** [comment]
I think it would be a good idea to merge `no-array-mutation` and `no-object-mutation` together into a single rule. Both these rules are quite similar under the hood and preform many of the same checks.

`readonly-keyword` and `readonly-array` could also potentially be merged.

**Comment by RebeccaStevens** [comment]
With regard to naming rule guidelines, I think I was making assumptions after seeing a rule at some point deprecated in favour of another rule that wasn't prefixed with `no-` in eslint itself. So disregard where I said `no-` prefixes are being moved way form.

That being said, in case where we can give a rule a non-negative asserting name, I think that would be preferable to a negative asserting one. *- I have know idea if "negative asserting" is the right term or not.*

**Comment by jonaskello** [comment]
I've been thinking a bit about these changes and some of the other changes being discussed and perhaps we're trying to work too much change into 1.0.0. Another way to look at it would be to make 1.0.0 more like tslint-immutable and then work with more changes for coming major versions (2.0.0 and forward). Having a 1.0.0 that is closer to tslint-immutable would make it easier to migrate and we would probably get faster to a stable 1.0.0 release so ppl can start using it. Making major changes takes some time, not only because of technical reasons but also the changes need to be discussed, we need to reflect on them and they need to mature. Not saying we need to keep everything exactly as in tslint-immutable though. Some changes are of course good, I guess I'm just trying to get to 1.0.0 a bit faster :-).

**Comment by RebeccaStevens** [comment]
@jonaskello I think everything is basically done now for a 1.0 release. 
We may want to finish and merge #60 before the release but that's not a biggy.

I'll create a release candidate now.

I'll close this issue now and we can open up new issues for any further changes.

**Comment by jonaskello** [comment]
@RebeccaStevens A big thank you for all the work you have put in to port the rules! 👍

Agreed #60 could be merged after release. I'll go ahead and put the release candidate to use in some of the larger projects I'm working on as soon as I can to get a feel for the stability etc. Just need to migrate the projects from tslint to eslint first :-)
