### ISSUE TITLE
Using with DOM API? What's the best practice?

### ISSUE THREAD

**Issue by baptisteArno** [jonaskello/eslint-plugin-functional#224]
First of all, thank you for this linter, it's helping me a lot to understand how to code functional programs. 🍻

I had a question though and I know it has nothing to do here but I think you can help me:

```ts
export const createIframe = ({
  backgroundColor = "transparent",
  ...iframeParams
}: IframeParams): HTMLElement => {
  const { publishId, customDomain, starterVariables } = iframeParams;
 const iframe = document.createElement("iframe");

  const hostName = customDomain ?? `${publishId}.typebot.io`;
  const iframeUrl = `https://${hostName}${parseQueryParams(starterVariables)}`;
  // eslint-disable-next-line functional/no-expression-statement
  iframe.setAttribute("src", iframeUrl);

  // eslint-disable-next-line functional/no-expression-statement, functional/immutable-data
  iframe.style.backgroundColor = backgroundColor;

  return iframe;
};
```

This linter seems hard to use with DOM manipulation. I'd like to know what's the best practice here?

**Comment by RebeccaStevens** [comment]
DOM elements and many other APIs are OO designed and unfortunately we can't write purely functional code to work with these.

Often the best approach is to simply use imperative programming in these cases and configure the rules to ignore these where possible.
For example, you might want to rename `iframe` to `domIframe` (or more generically `mutableIframe`) and configure `immutable-data` to ignore data that start with `dom`.

If you really want to make things functional, you could set up a black-box system; where all imperative code lives inside the black-box and functional endpoints are exposed for the rest of the code to use. This make it so that from the perspective of the rest of the code, everything is still functional.

**Comment by baptisteArno** [comment]
Thank you very much for taking the time to answer 🙏
