### ISSUE TITLE
Dependabot PR are not being automerged

### ISSUE THREAD

**Issue by RebeccaStevens** [jonaskello/eslint-plugin-functional#253]
PRs opened by dependabot are not being automatically merged. This seems to be because the github actions don't have permission to merge the PRs. To resolve this, it seems that an access token needs to be added.

The token needs to be added as a secret and then [specified on this line](https://github.com/jonaskello/eslint-plugin-functional/blob/master/.github/workflows/dependabot-automerge.yml#L25). (Currently it's setup to use github actions' auth).

@jonaskello, would you be able to set this up?

[Here's a comment by the action author about the issue](https://github.com/pascalgn/automerge-action/issues/150#issuecomment-890815491)

I don't know if we can keep it so that a bot is merging the PRs instead of a maintainer.

**Comment by jonaskello** [comment]
I did some digging about this. Seems like the reason why dependabot cannot merge is that GITHUB_TOKEN only gives read-only permission when the PR is from a forked repo. See the "Maximum accessby forked repos" in [this article](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token). Dependabot seems to fork to its own repo and then create a PR from that. It has been possible to work around this by using a personal access token instead of GITHUB_TOKEN (as was suggested by the action author in your link above) but if I understand [this post](https://jongleberry.medium.com/accessing-github-actions-secrets-for-dependabot-pull-requests-on-private-repositories-b0dd6995f21b) correctly it is now disabled by default because of security reasons (the article is about private repos but I think the core issue applies to public repos too). I'm not sure how to solve this. I think it would work if I add a personal access token and also enable "Send secrets to workflows from fork pull requests" but that might lead secrets? There is some more info in [this page](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/).

**Comment by jonaskello** [comment]
According to the [last link in my previous post](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/) I think changing the workflow trigger from `pull_request` to `pull_request_target` might work?

**Comment by RebeccaStevens** [comment]
I gave that article a quick scan through and I think it reasonably safe for this project to just use `pull_request_target`. It's your call though.

**Comment by jonaskello** [comment]
So I changed to `pull_request_target`. From what I understand this should make the action run in the context of this repo rather than the fork and therefore give dependabot a write token in `GITHUB_TOKEN`. Let's see if it works :-).
