### ISSUE TITLE
new rule: prefer-type

### ISSUE THREAD

**Issue by RebeccaStevens** [jonaskello/eslint-plugin-functional#35]
Interfaces are part of object oriented design.
In functional programming, Types should be used instead.

See jonaskello/tslint-immutable#4 for previous discussion.

**Comment by jonaskello** [comment]
When I started out in typescript some years ago I used `type` everywhere because I thought it was nicer than `interface`. However I soon realised the error messages involving `type` became very hard to read because they repeated the whole type definition while interface error messages just used the interface name. So I switched to use `interface` as much as possible and haven't thought about it since then. I guess the same is true for other ppl that started out before 2.1.

I did some research now and I found this [blog post](https://medium.com/@martin_hotell/interface-vs-type-alias-in-typescript-2-7-2a8f1777af4c) that does a more recent comparison between `type` and `interface` and it says the error message problem is not present anymore since typescript 2.1. So I guess I may start using `type` everywhere again :-). More importantly, as you can implement interfaces with classes etc. I agree `type` is more functional. Also you need to use `type` to use ADTs (union and intersection types) so if you want to use only one it has to be `type`.

If it is part of `no-class` I guess you cannot disallow interface without also disallowing class but perhaps this is not a useful scenario. If we make a separate `no-interface` or `prefer-type` rule it could be consumed in isolation. We could also change `no-class` into `no-oo` and have options for both class and interface.  I'm finding it increasingly difficult to reason about how to split/merge the rules, I think we should come up with some design guidelines in this area. Anyway, disallowing interface would fall under the "No OO" theme.

**Comment by RebeccaStevens** [comment]
Those are some really good points.
I think having a `no-oo` rule with a bunch of options might be the best approach.

**Comment by RebeccaStevens** [comment]
After reflecting on this, I think the best option is to simply create a new rule. Let's keep no oo as a category rather than a rule.
